#!/bin/sh

if [ -z "${ANSIBLE_HOME}" ]
then
    echo "ANSIBLE_HOME is undefined. Go into ansible directory and run 'source hacking/env-setup'"
    exit 1
fi

cp ${ANSIBLE_HOME}/test/units/modules/network/pfsense/*.py test/units/modules/network/pfsense/
cp ${ANSIBLE_HOME}/test/units/modules/network/pfsense/fixtures/*.xml test/units/modules/network/pfsense/fixtures/
cp ${ANSIBLE_HOME}/lib/ansible/module_utils/network/pfsense/*.py module_utils/network/pfsense/
cp ${ANSIBLE_HOME}/lib/ansible/modules/network/pfsense/*.py library/
cp ${ANSIBLE_HOME}/lib/ansible/plugins/lookup/pfsense.py lookup_plugins/pfsense.py
