#!/bin/bash

[ ! -d ansible-pfsense ] && echo "No such directory ansible-pfsense" && exit 1
[ ! -d pfsensible/core ] && echo "No such directory pfsensible/core" && exit 1

rm -rf pfsensible/core/{examples,misc,plugins,tests/units/modules,*.tar.gz}
mkdir -p pfsensible/core/{examples,misc,plugins/modules,tests/units/modules}
cp -a ansible-pfsense/{.gitignore,LICENSE} pfsensible/core/
cp -a ansible-pfsense/{pfsense.yml,pfsense_setup.yml,roles} pfsensible/core/examples/
cp -a ansible-pfsense/lookup_plugins pfsensible/core/plugins/lookup
cp -a ansible-pfsense/module_utils/network/pfsense pfsensible/core/plugins/module_utils
cp -a ansible-pfsense/test/units/modules/network/pfsense/* pfsensible/core/tests/units/modules/
cp -a ansible-pfsense/library/*.py pfsensible/core/plugins/modules/

# for path in ansible-pfsense/library/*.py
# do
#   filename=${path##*/}
#   cp -a $path pfsensible/core/plugins/modules/${filename/pfsense_/}
# done

sed -I .orig -e 's/pfsense_/pfsensible.core./g' -e s,opoplawski/ansible-pfsense,pfsensible/core, pfsensible/core/README.md
sed -I .orig -e 's/pfsense_\(.*:\)/pfsensible.core.\1/g' $(find pfsensible/core/examples -name \*.yml)
sed -I .orig -e '/import\|module:\|^ *pfsense_[a-z_0-9]*:$\|descr *= *.ansible pfsense_/s/pfsense_/pfsensible.core./' $(find pfsensible/core/plugins/modules -name \*.py)
sed -I .orig -e '/self.name = /s/pfsense_/pfsensible.core./' $(find pfsensible/core -name \*.py)
sed -I .orig -e s/ansible.module_utils.network.pfsense/ansible_collections.pfsensible.core.plugins.module_utils/ $(find pfsensible -name \*.py)
sed -I .orig -e 's/ansible.modules.network.pfsense import pfsense_/ansible_collections.pfsensible.core import /' $(find pfsensible/core/tests -name \*.py)
find pfsensible/core -name \*.orig -delete

cd pfsensible/core
ansible-galaxy collection build
