#!/bin/bash

mkdir -p {examples,misc,plugins,tests/unit/modules}
git mv library plugins/modules
git mv module_utils/network/pfsense plugins/module_utils
git rm -r module_utils
rm -rf module_utils
git mv {group_vars,pfsense.yml,pfsense_setup.yml,roles} examples/
git mv lookup_plugins plugins/lookup/
git mv test/units/modules/network/pfsense/* tests/unit/modules/
git mv test/units/plugins tests/unit/
git rm -r test
rm -r test

sed -i -e 's/pfsense_/pfsensible.core.pfsense_/g' -e s,opoplawski/ansible-pfsense,pfsensible/core, README.md
sed -i -e 's/\(pfsense_.*:\)/pfsensible.core.\1/g' $(find examples -name \*.yml)
#sed -i -e '/import\|module:\|^ *pfsense_[a-z_0-9]*:$\|descr *= *.ansible pfsense_/s/pfsense_/pfsensible.core./' $(find pfsensible/core/plugins/modules -name \*.py)
sed -i -e '/self.name = /s/pfsense_/pfsensible.core.pfsense_/' \
       -e s/ansible.module_utils.network.pfsense/ansible_collections.pfsensible.core.plugins.module_utils/ \
       -e s/ansible.module_utils.compat.ipaddress/ansible_collections.ansible.netcommon.plugins.module_utils.compat.ipaddress/ \
       -e 's/ansible.modules.network.pfsense import /ansible_collections.pfsensible.core import /' $(find tests -name \*.py)

rm -f pfsensible-core-*.tar.gz
ansible-galaxy collection build
